In [46]:
import pandas as pd

In [47]:
data=pd.read_csv('../data/vehicles.csv')
print(data.info())

<class 'pandas.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 26 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            426880 non-null  int64
 1   url           426880 non-null  str
 2   region        426880 non-null  str
 3   region_url    426880 non-null  str
 4   price         426880 non-null  int64
 5   year          425675 non-null  float64
 6   manufacturer  409234 non-null  str
 7   model         421603 non-null  str
 8   condition     252776 non-null  str
 9   cylinders     249202 non-null  str
 10  fuel          423867 non-null  str
 11  odometer      422480 non-null  float64
 12  title_status  418638 non-null  str
 13  transmission  424324 non-null  str
 14  VIN           265838 non-null  str
 15  drive         296313 non-null  str
 16  size          120519 non-null  str
 17  type          334022 non-null  str
 18  paint_color   296677 non-null  str
 19  image_url     426812 non-null  str
 20  description   426810 non-null  str
 21  county        0 non-null       float64
 22  state         426880 non-null  str
 23  lat           420331 non-null  float64
 24  long          420331 non-null  float64
 25  posting_date  426812 non-null  str
dtypes: float64(5), int64(2), str(19)
memory usage: 84.7 MB
None

In [48]:
data

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,fuel,odometer,title_status,transmission,VIN,drive,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
0,7222695916,https://prescott.craigslist.org/cto/d/prescott...,prescott,https://prescott.craigslist.org,6000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,az,NaN,NaN,NaN
1,7218891961,https://fayar.craigslist.org/ctd/d/bentonville...,fayetteville,https://fayar.craigslist.org,11900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ar,NaN,NaN,NaN
2,7221797935,https://keys.craigslist.org/cto/d/summerland-k...,florida keys,https://keys.craigslist.org,21000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fl,NaN,NaN,NaN
3,7222270760,https://worcester.craigslist.org/cto/d/west-br...,worcester / central MA,https://worcester.craigslist.org,1500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ma,NaN,NaN,NaN
4,7210384030,https://greensboro.craigslist.org/cto/d/trinit...,greensboro,https://greensboro.craigslist.org,4900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nc,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426875,7301591192,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,23590,2019.0,nissan,maxima s sedan 4d,good,6 cylinders,gas,32226.0,clean,other,1N4AA6AV6KC367801,fwd,NaN,sedan,NaN,https://images.craigslist.org/00o0o_iiraFnHg8q...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:31-0600
426876,7301591187,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,30590,2020.0,volvo,s60 t5 momentum sedan 4d,good,NaN,gas,12029.0,clean,other,7JR102FKXLG042696,fwd,NaN,sedan,red,https://images.craigslist.org/00x0x_15sbgnxCIS...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:29-0600
426877,7301591147,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,34990,2020.0,cadillac,xt4 sport suv 4d,good,NaN,diesel,4174.0,clean,other,1GYFZFR46LF088296,NaN,NaN,hatchback,white,https://images.craigslist.org/00L0L_farM7bxnxR...,Carvana is the safer way to buy a car During t...,NaN,wy,33.779214,-84.411811,2021-04-04T03:21:17-0600
426878,7301591140,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,28990,2018.0,lexus,es 350 sedan 4d,good,6 cylinders,gas,30112.0,clean,other,58ABK1GG4JU103853,fwd,NaN,sedan,silver,https://images.craigslist.org/00z0z_bKnIVGLkDT...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:11-0600
426879,7301591129,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,30590,2019.0,bmw,4 series 430i gran coupe,good,NaN,gas,22716.0,clean,other,WBA4J1C58KBM14708,rwd,NaN,coupe,NaN,https://images.craigslist.org/00Y0Y_lEUocjyRxa...,Carvana is the safer way to buy a car During t...,NaN,wy,33.779214,-84.411811,2021-04-04T03:21:07-0600

In [49]:
data=data.drop(columns=["id","url","region_url","lat","long","paint_color","image_url","description","VIN","posting_date","region","county"])

In [50]:
pd.set_option('display.max_columns', None)
data.tail(5)

,price,year,manufacturer,model,condition,cylinders,fuel,odometer,title_status,transmission,drive,size,type,state
426875,23590,2019.0,nissan,maxima s sedan 4d,good,6 cylinders,gas,32226.0,clean,other,fwd,NaN,sedan,wy
426876,30590,2020.0,volvo,s60 t5 momentum sedan 4d,good,NaN,gas,12029.0,clean,other,fwd,NaN,sedan,wy
426877,34990,2020.0,cadillac,xt4 sport suv 4d,good,NaN,diesel,4174.0,clean,other,NaN,NaN,hatchback,wy
426878,28990,2018.0,lexus,es 350 sedan 4d,good,6 cylinders,gas,30112.0,clean,other,fwd,NaN,sedan,wy
426879,30590,2019.0,bmw,4 series 430i gran coupe,good,NaN,gas,22716.0,clean,other,rwd,NaN,coupe,wy

In [51]:
data.info()
data["transmission"].unique()
data["state"].unique()

<class 'pandas.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   price         426880 non-null  int64
 1   year          425675 non-null  float64
 2   manufacturer  409234 non-null  str
 3   model         421603 non-null  str
 4   condition     252776 non-null  str
 5   cylinders     249202 non-null  str
 6   fuel          423867 non-null  str
 7   odometer      422480 non-null  float64
 8   title_status  418638 non-null  str
 9   transmission  424324 non-null  str
 10  drive         296313 non-null  str
 11  size          120519 non-null  str
 12  type          334022 non-null  str
 13  state         426880 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 45.6 MB

<StringArray>
['az', 'ar', 'fl', 'ma', 'nc', 'ny', 'or', 'pa', 'tx', 'wa', 'wi', 'al', 'ak',
 'ca', 'co', 'ct', 'dc', 'de', 'ga', 'hi', 'id', 'il', 'in', 'ia', 'ks', 'ky',
 'la', 'me', 'md', 'mi', 'mn', 'ms', 'mo', 'mt', 'ne', 'nv', 'nj', 'nm', 'nh',
 'nd', 'oh', 'ok', 'ri', 'sc', 'sd', 'tn', 'ut', 'vt', 'va', 'wv', 'wy']
Length: 51, dtype: str

In [52]:
#data.tail().sort_values(by="model")
boolean= not data["model"].is_unique
boolean

True

In [53]:
mask_man = data[["manufacturer", "model"]].dropna()
model2man=dict(zip(mask_man["model"], mask_man["manufacturer"]))
data["manufacturer"]=data["manufacturer"].fillna(data["model"].map(model2man))
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   price         426880 non-null  int64
 1   year          425675 non-null  float64
 2   manufacturer  410002 non-null  str
 3   model         421603 non-null  str
 4   condition     252776 non-null  str
 5   cylinders     249202 non-null  str
 6   fuel          423867 non-null  str
 7   odometer      422480 non-null  float64
 8   title_status  418638 non-null  str
 9   transmission  424324 non-null  str
 10  drive         296313 non-null  str
 11  size          120519 non-null  str
 12  type          334022 non-null  str
 13  state         426880 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 45.6 MB

In [54]:
data.duplicated().any()
data=data.drop_duplicates()
data.info()

<class 'pandas.DataFrame'>
Index: 298865 entries, 0 to 426879
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   price         298865 non-null  int64
 1   year          297996 non-null  float64
 2   manufacturer  286407 non-null  str
 3   model         294619 non-null  str
 4   condition     185416 non-null  str
 5   cylinders     182847 non-null  str
 6   fuel          296984 non-null  str
 7   odometer      296202 non-null  float64
 8   title_status  294161 non-null  str
 9   transmission  297262 non-null  str
 10  drive         210683 non-null  str
 11  size          94675 non-null   str
 12  type          230068 non-null  str
 13  state         298865 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 34.2 MB

In [55]:
mask_size=data[["size", "model"]].dropna()
size_dict=dict(zip(mask_size["model"], mask_size["size"]))
data["size"]=data["size"].fillna(data["model"].map(size_dict))

data.info()

<class 'pandas.DataFrame'>
Index: 298865 entries, 0 to 426879
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   price         298865 non-null  int64
 1   year          297996 non-null  float64
 2   manufacturer  286407 non-null  str
 3   model         294619 non-null  str
 4   condition     185416 non-null  str
 5   cylinders     182847 non-null  str
 6   fuel          296984 non-null  str
 7   odometer      296202 non-null  float64
 8   title_status  294161 non-null  str
 9   transmission  297262 non-null  str
 10  drive         210683 non-null  str
 11  size          242947 non-null  str
 12  type          230068 non-null  str
 13  state         298865 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 34.2 MB

In [56]:
mask_size=data[["model", "drive"]].dropna()
size_dict=dict(zip(mask_size["model"], mask_size["drive"]))
data["drive"]=data["drive"].fillna(data["model"].map(size_dict))

data.info()

<class 'pandas.DataFrame'>
Index: 298865 entries, 0 to 426879
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   price         298865 non-null  int64
 1   year          297996 non-null  float64
 2   manufacturer  286407 non-null  str
 3   model         294619 non-null  str
 4   condition     185416 non-null  str
 5   cylinders     182847 non-null  str
 6   fuel          296984 non-null  str
 7   odometer      296202 non-null  float64
 8   title_status  294161 non-null  str
 9   transmission  297262 non-null  str
 10  drive         282213 non-null  str
 11  size          242947 non-null  str
 12  type          230068 non-null  str
 13  state         298865 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 34.2 MB

In [57]:
mask_size=data[["model", "type"]].dropna()
size_dict=dict(zip(mask_size["model"], mask_size["type"]))
data["type"]=data["type"].fillna(data["model"].map(size_dict))

data.info()

<class 'pandas.DataFrame'>
Index: 298865 entries, 0 to 426879
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   price         298865 non-null  int64
 1   year          297996 non-null  float64
 2   manufacturer  286407 non-null  str
 3   model         294619 non-null  str
 4   condition     185416 non-null  str
 5   cylinders     182847 non-null  str
 6   fuel          296984 non-null  str
 7   odometer      296202 non-null  float64
 8   title_status  294161 non-null  str
 9   transmission  297262 non-null  str
 10  drive         282213 non-null  str
 11  size          242947 non-null  str
 12  type          289765 non-null  str
 13  state         298865 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 34.2 MB

In [58]:
mask_size = data[["model", "cylinders"]].dropna()
size_dict = dict(zip(mask_size["model"], mask_size["cylinders"]))
data["cylinders"] = data["cylinders"].fillna(data["model"].map(size_dict))

data.info()

<class 'pandas.DataFrame'>
Index: 298865 entries, 0 to 426879
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   price         298865 non-null  int64
 1   year          297996 non-null  float64
 2   manufacturer  286407 non-null  str
 3   model         294619 non-null  str
 4   condition     185416 non-null  str
 5   cylinders     273027 non-null  str
 6   fuel          296984 non-null  str
 7   odometer      296202 non-null  float64
 8   title_status  294161 non-null  str
 9   transmission  297262 non-null  str
 10  drive         282213 non-null  str
 11  size          242947 non-null  str
 12  type          289765 non-null  str
 13  state         298865 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 34.2 MB

In [59]:
mask_size = data[["model", "condition"]].dropna()
size_dict = dict(zip(mask_size["model"], mask_size["condition"]))
data["condition"] = data["condition"].fillna(data["model"].map(size_dict))

data.info()

<class 'pandas.DataFrame'>
Index: 298865 entries, 0 to 426879
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   price         298865 non-null  int64
 1   year          297996 non-null  float64
 2   manufacturer  286407 non-null  str
 3   model         294619 non-null  str
 4   condition     282029 non-null  str
 5   cylinders     273027 non-null  str
 6   fuel          296984 non-null  str
 7   odometer      296202 non-null  float64
 8   title_status  294161 non-null  str
 9   transmission  297262 non-null  str
 10  drive         282213 non-null  str
 11  size          242947 non-null  str
 12  type          289765 non-null  str
 13  state         298865 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 34.2 MB

In [60]:
print(data["manufacturer"].nunique())
print(data["model"].nunique())

42
29667

In [61]:
#we are going to use one-hot-encoding technique for manufacturer and frequency-encoding for model
data=pd.get_dummies(data,columns=["manufacturer"])
data.loc[2000,data.columns.str.startswith("manufacturer")]
frequency=data["model"].value_counts(normalize=True)
data['model_frequency']=data["model"].map(frequency)
data.tail(3)

,price,year,model,condition,cylinders,fuel,odometer,title_status,transmission,drive,size,type,state,manufacturer_acura,manufacturer_alfa-romeo,manufacturer_aston-martin,manufacturer_audi,manufacturer_bmw,manufacturer_buick,manufacturer_cadillac,manufacturer_chevrolet,manufacturer_chrysler,manufacturer_datsun,manufacturer_dodge,manufacturer_ferrari,manufacturer_fiat,manufacturer_ford,manufacturer_gmc,manufacturer_harley-davidson,manufacturer_honda,manufacturer_hyundai,manufacturer_infiniti,manufacturer_jaguar,manufacturer_jeep,manufacturer_kia,manufacturer_land rover,manufacturer_lexus,manufacturer_lincoln,manufacturer_mazda,manufacturer_mercedes-benz,manufacturer_mercury,manufacturer_mini,manufacturer_mitsubishi,manufacturer_morgan,manufacturer_nissan,manufacturer_pontiac,manufacturer_porsche,manufacturer_ram,manufacturer_rover,manufacturer_saturn,manufacturer_subaru,manufacturer_tesla,manufacturer_toyota,manufacturer_volkswagen,manufacturer_volvo,model_frequency
426877,34990,2020.0,xt4 sport suv 4d,good,NaN,diesel,4174.0,clean,other,fwd,NaN,hatchback,wy,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0.000645
426878,28990,2018.0,es 350 sedan 4d,good,6 cylinders,gas,30112.0,clean,other,fwd,NaN,sedan,wy,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0.000428
426879,30590,2019.0,4 series 430i gran coupe,good,NaN,gas,22716.0,clean,other,rwd,NaN,coupe,wy,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0.000068

In [62]:
data.info()

<class 'pandas.DataFrame'>
Index: 298865 entries, 0 to 426879
Data columns (total 56 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   price                         298865 non-null  int64
 1   year                          297996 non-null  float64
 2   model                         294619 non-null  str
 3   condition                     282029 non-null  str
 4   cylinders                     273027 non-null  str
 5   fuel                          296984 non-null  str
 6   odometer                      296202 non-null  float64
 7   title_status                  294161 non-null  str
 8   transmission                  297262 non-null  str
 9   drive                         282213 non-null  str
 10  size                          242947 non-null  str
 11  type                          289765 non-null  str
 12  state                         298865 non-null  str
 13  manufacturer_acura            298865 non-null  bool
 14  manufacturer_alfa-romeo       298865 non-null  bool
 15  manufacturer_aston-martin     298865 non-null  bool
 16  manufacturer_audi             298865 non-null  bool
 17  manufacturer_bmw              298865 non-null  bool
 18  manufacturer_buick            298865 non-null  bool
 19  manufacturer_cadillac         298865 non-null  bool
 20  manufacturer_chevrolet        298865 non-null  bool
 21  manufacturer_chrysler         298865 non-null  bool
 22  manufacturer_datsun           298865 non-null  bool
 23  manufacturer_dodge            298865 non-null  bool
 24  manufacturer_ferrari          298865 non-null  bool
 25  manufacturer_fiat             298865 non-null  bool
 26  manufacturer_ford             298865 non-null  bool
 27  manufacturer_gmc              298865 non-null  bool
 28  manufacturer_harley-davidson  298865 non-null  bool
 29  manufacturer_honda            298865 non-null  bool
 30  manufacturer_hyundai          298865 non-null  bool
 31  manufacturer_infiniti         298865 non-null  bool
 32  manufacturer_jaguar           298865 non-null  bool
 33  manufacturer_jeep             298865 non-null  bool
 34  manufacturer_kia              298865 non-null  bool
 35  manufacturer_land rover       298865 non-null  bool
 36  manufacturer_lexus            298865 non-null  bool
 37  manufacturer_lincoln          298865 non-null  bool
 38  manufacturer_mazda            298865 non-null  bool
 39  manufacturer_mercedes-benz    298865 non-null  bool
 40  manufacturer_mercury          298865 non-null  bool
 41  manufacturer_mini             298865 non-null  bool
 42  manufacturer_mitsubishi       298865 non-null  bool
 43  manufacturer_morgan           298865 non-null  bool
 44  manufacturer_nissan           298865 non-null  bool
 45  manufacturer_pontiac          298865 non-null  bool
 46  manufacturer_porsche          298865 non-null  bool
 47  manufacturer_ram              298865 non-null  bool
 48  manufacturer_rover            298865 non-null  bool
 49  manufacturer_saturn           298865 non-null  bool
 50  manufacturer_subaru           298865 non-null  bool
 51  manufacturer_tesla            298865 non-null  bool
 52  manufacturer_toyota           298865 non-null  bool
 53  manufacturer_volkswagen       298865 non-null  bool
 54  manufacturer_volvo            298865 non-null  bool
 55  model_frequency               294619 non-null  float64
dtypes: bool(42), float64(3), int64(1), str(10)
memory usage: 54.2 MB

In [63]:
#one hot encoding for state

data=pd.get_dummies(data,columns=["state"])

#making age column
data["age"]=2026-data["year"]
data=data.drop(columns=["model","year"])

In [64]:

data=pd.get_dummies(data,columns=["transmission"])
for i, col in enumerate(data.columns):
    print(i, col,data[col].dtype)

0 price int64
1 condition str
2 cylinders str
3 fuel str
4 odometer float64
5 title_status str
6 drive str
7 size str
8 type str
9 manufacturer_acura bool
10 manufacturer_alfa-romeo bool
11 manufacturer_aston-martin bool
12 manufacturer_audi bool
13 manufacturer_bmw bool
14 manufacturer_buick bool
15 manufacturer_cadillac bool
16 manufacturer_chevrolet bool
17 manufacturer_chrysler bool
18 manufacturer_datsun bool
19 manufacturer_dodge bool
20 manufacturer_ferrari bool
21 manufacturer_fiat bool
22 manufacturer_ford bool
23 manufacturer_gmc bool
24 manufacturer_harley-davidson bool
25 manufacturer_honda bool
26 manufacturer_hyundai bool
27 manufacturer_infiniti bool
28 manufacturer_jaguar bool
29 manufacturer_jeep bool
30 manufacturer_kia bool
31 manufacturer_land rover bool
32 manufacturer_lexus bool
33 manufacturer_lincoln bool
34 manufacturer_mazda bool
35 manufacturer_mercedes-benz bool
36 manufacturer_mercury bool
37 manufacturer_mini bool
38 manufacturer_mitsubishi bool
39 manufacturer_morgan bool
40 manufacturer_nissan bool
41 manufacturer_pontiac bool
42 manufacturer_porsche bool
43 manufacturer_ram bool
44 manufacturer_rover bool
45 manufacturer_saturn bool
46 manufacturer_subaru bool
47 manufacturer_tesla bool
48 manufacturer_toyota bool
49 manufacturer_volkswagen bool
50 manufacturer_volvo bool
51 model_frequency float64
52 state_ak bool
53 state_al bool
54 state_ar bool
55 state_az bool
56 state_ca bool
57 state_co bool
58 state_ct bool
59 state_dc bool
60 state_de bool
61 state_fl bool
62 state_ga bool
63 state_hi bool
64 state_ia bool
65 state_id bool
66 state_il bool
67 state_in bool
68 state_ks bool
69 state_ky bool
70 state_la bool
71 state_ma bool
72 state_md bool
73 state_me bool
74 state_mi bool
75 state_mn bool
76 state_mo bool
77 state_ms bool
78 state_mt bool
79 state_nc bool
80 state_nd bool
81 state_ne bool
82 state_nh bool
83 state_nj bool
84 state_nm bool
85 state_nv bool
86 state_ny bool
87 state_oh bool
88 state_ok bool
89 state_or bool
90 state_pa bool
91 state_ri bool
92 state_sc bool
93 state_sd bool
94 state_tn bool
95 state_tx bool
96 state_ut bool
97 state_va bool
98 state_vt bool
99 state_wa bool
100 state_wi bool
101 state_wv bool
102 state_wy bool
103 age float64
104 transmission_automatic bool
105 transmission_manual bool
106 transmission_other bool

In [65]:
data["size"].unique()
data["cylinders"].unique()

data=data[data["cylinders"]!='other']
data["cylinders"]=data["cylinders"].str.replace("cylinders","")
data["cylinders"]=pd.to_numeric(data["cylinders"],errors="coerce")

data["cylinders"].value_counts()

cylinders
6.0     97005
4.0     93030
8.0     76385
5.0      2295
3.0      1188
10.0     1159
12.0      193
Name: count, dtype: int64

In [66]:
for i, col in enumerate(data.columns):
    print(i, col,data[col].dtype)

0 price int64
1 condition str
2 cylinders float64
3 fuel str
4 odometer float64
5 title_status str
6 drive str
7 size str
8 type str
9 manufacturer_acura bool
10 manufacturer_alfa-romeo bool
11 manufacturer_aston-martin bool
12 manufacturer_audi bool
13 manufacturer_bmw bool
14 manufacturer_buick bool
15 manufacturer_cadillac bool
16 manufacturer_chevrolet bool
17 manufacturer_chrysler bool
18 manufacturer_datsun bool
19 manufacturer_dodge bool
20 manufacturer_ferrari bool
21 manufacturer_fiat bool
22 manufacturer_ford bool
23 manufacturer_gmc bool
24 manufacturer_harley-davidson bool
25 manufacturer_honda bool
26 manufacturer_hyundai bool
27 manufacturer_infiniti bool
28 manufacturer_jaguar bool
29 manufacturer_jeep bool
30 manufacturer_kia bool
31 manufacturer_land rover bool
32 manufacturer_lexus bool
33 manufacturer_lincoln bool
34 manufacturer_mazda bool
35 manufacturer_mercedes-benz bool
36 manufacturer_mercury bool
37 manufacturer_mini bool
38 manufacturer_mitsubishi bool
39 manufacturer_morgan bool
40 manufacturer_nissan bool
41 manufacturer_pontiac bool
42 manufacturer_porsche bool
43 manufacturer_ram bool
44 manufacturer_rover bool
45 manufacturer_saturn bool
46 manufacturer_subaru bool
47 manufacturer_tesla bool
48 manufacturer_toyota bool
49 manufacturer_volkswagen bool
50 manufacturer_volvo bool
51 model_frequency float64
52 state_ak bool
53 state_al bool
54 state_ar bool
55 state_az bool
56 state_ca bool
57 state_co bool
58 state_ct bool
59 state_dc bool
60 state_de bool
61 state_fl bool
62 state_ga bool
63 state_hi bool
64 state_ia bool
65 state_id bool
66 state_il bool
67 state_in bool
68 state_ks bool
69 state_ky bool
70 state_la bool
71 state_ma bool
72 state_md bool
73 state_me bool
74 state_mi bool
75 state_mn bool
76 state_mo bool
77 state_ms bool
78 state_mt bool
79 state_nc bool
80 state_nd bool
81 state_ne bool
82 state_nh bool
83 state_nj bool
84 state_nm bool
85 state_nv bool
86 state_ny bool
87 state_oh bool
88 state_ok bool
89 state_or bool
90 state_pa bool
91 state_ri bool
92 state_sc bool
93 state_sd bool
94 state_tn bool
95 state_tx bool
96 state_ut bool
97 state_va bool
98 state_vt bool
99 state_wa bool
100 state_wi bool
101 state_wv bool
102 state_wy bool
103 age float64
104 transmission_automatic bool
105 transmission_manual bool
106 transmission_other bool

In [67]:
data["condition"].unique()
data=pd.get_dummies(data,columns=["condition"])

In [68]:
data["drive"].unique()
data=pd.get_dummies(data,columns=["drive"])

In [69]:
data["type"].unique()
data=pd.get_dummies(data,columns=["type"])

In [70]:
data=pd.get_dummies(data,columns=["size"])

In [71]:
data["title_status"].unique()
data=pd.get_dummies(data,columns=["title_status"])

In [72]:
data["fuel"].unique()
data=pd.get_dummies(data,columns=["fuel"])

In [73]:
data=data.dropna()

In [79]:
for i, col in enumerate(data.columns):
    print(i,col,data[col].dtype, data[col].isna().sum())
data.shape

0 price int64 0
1 cylinders float64 0
2 odometer float64 0
3 manufacturer_acura bool 0
4 manufacturer_alfa-romeo bool 0
5 manufacturer_aston-martin bool 0
6 manufacturer_audi bool 0
7 manufacturer_bmw bool 0
8 manufacturer_buick bool 0
9 manufacturer_cadillac bool 0
10 manufacturer_chevrolet bool 0
11 manufacturer_chrysler bool 0
12 manufacturer_datsun bool 0
13 manufacturer_dodge bool 0
14 manufacturer_ferrari bool 0
15 manufacturer_fiat bool 0
16 manufacturer_ford bool 0
17 manufacturer_gmc bool 0
18 manufacturer_harley-davidson bool 0
19 manufacturer_honda bool 0
20 manufacturer_hyundai bool 0
21 manufacturer_infiniti bool 0
22 manufacturer_jaguar bool 0
23 manufacturer_jeep bool 0
24 manufacturer_kia bool 0
25 manufacturer_land rover bool 0
26 manufacturer_lexus bool 0
27 manufacturer_lincoln bool 0
28 manufacturer_mazda bool 0
29 manufacturer_mercedes-benz bool 0
30 manufacturer_mercury bool 0
31 manufacturer_mini bool 0
32 manufacturer_mitsubishi bool 0
33 manufacturer_morgan bool 0
34 manufacturer_nissan bool 0
35 manufacturer_pontiac bool 0
36 manufacturer_porsche bool 0
37 manufacturer_ram bool 0
38 manufacturer_rover bool 0
39 manufacturer_saturn bool 0
40 manufacturer_subaru bool 0
41 manufacturer_tesla bool 0
42 manufacturer_toyota bool 0
43 manufacturer_volkswagen bool 0
44 manufacturer_volvo bool 0
45 model_frequency float64 0
46 state_ak bool 0
47 state_al bool 0
48 state_ar bool 0
49 state_az bool 0
50 state_ca bool 0
51 state_co bool 0
52 state_ct bool 0
53 state_dc bool 0
54 state_de bool 0
55 state_fl bool 0
56 state_ga bool 0
57 state_hi bool 0
58 state_ia bool 0
59 state_id bool 0
60 state_il bool 0
61 state_in bool 0
62 state_ks bool 0
63 state_ky bool 0
64 state_la bool 0
65 state_ma bool 0
66 state_md bool 0
67 state_me bool 0
68 state_mi bool 0
69 state_mn bool 0
70 state_mo bool 0
71 state_ms bool 0
72 state_mt bool 0
73 state_nc bool 0
74 state_nd bool 0
75 state_ne bool 0
76 state_nh bool 0
77 state_nj bool 0
78 state_nm bool 0
79 state_nv bool 0
80 state_ny bool 0
81 state_oh bool 0
82 state_ok bool 0
83 state_or bool 0
84 state_pa bool 0
85 state_ri bool 0
86 state_sc bool 0
87 state_sd bool 0
88 state_tn bool 0
89 state_tx bool 0
90 state_ut bool 0
91 state_va bool 0
92 state_vt bool 0
93 state_wa bool 0
94 state_wi bool 0
95 state_wv bool 0
96 state_wy bool 0
97 age float64 0
98 transmission_automatic bool 0
99 transmission_manual bool 0
100 transmission_other bool 0
101 condition_excellent bool 0
102 condition_fair bool 0
103 condition_good bool 0
104 condition_like new bool 0
105 condition_new bool 0
106 condition_salvage bool 0
107 drive_4wd bool 0
108 drive_fwd bool 0
109 drive_rwd bool 0
110 type_SUV bool 0
111 type_bus bool 0
112 type_convertible bool 0
113 type_coupe bool 0
114 type_hatchback bool 0
115 type_mini-van bool 0
116 type_offroad bool 0
117 type_other bool 0
118 type_pickup bool 0
119 type_sedan bool 0
120 type_truck bool 0
121 type_van bool 0
122 type_wagon bool 0
123 size_compact bool 0
124 size_full-size bool 0
125 size_mid-size bool 0
126 size_sub-compact bool 0
127 title_status_clean bool 0
128 title_status_lien bool 0
129 title_status_missing bool 0
130 title_status_parts only bool 0
131 title_status_rebuilt bool 0
132 title_status_salvage bool 0
133 fuel_diesel bool 0
134 fuel_electric bool 0
135 fuel_gas bool 0
136 fuel_hybrid bool 0
137 fuel_other bool 0

(265892, 138)

In [80]:
data.to_csv(path_or_buf='../data/vehicles_cleaned.csv')