In [82]:
import pandas as pd

In [83]:
data=pd.read_csv('../data/vehicles.csv')
print(data.info())

<class 'pandas.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 26 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            426880 non-null  int64
 1   url           426880 non-null  str
 2   region        426880 non-null  str
 3   region_url    426880 non-null  str
 4   price         426880 non-null  int64
 5   year          425675 non-null  float64
 6   manufacturer  409234 non-null  str
 7   model         421603 non-null  str
 8   condition     252776 non-null  str
 9   cylinders     249202 non-null  str
 10  fuel          423867 non-null  str
 11  odometer      422480 non-null  float64
 12  title_status  418638 non-null  str
 13  transmission  424324 non-null  str
 14  VIN           265838 non-null  str
 15  drive         296313 non-null  str
 16  size          120519 non-null  str
 17  type          334022 non-null  str
 18  paint_color   296677 non-null  str
 19  image_url     426812 non-null  str
 20  description   426810 non-null  str
 21  county        0 non-null       float64
 22  state         426880 non-null  str
 23  lat           420331 non-null  float64
 24  long          420331 non-null  float64
 25  posting_date  426812 non-null  str
dtypes: float64(5), int64(2), str(19)
memory usage: 84.7 MB
None

In [84]:
data

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,fuel,odometer,title_status,transmission,VIN,drive,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
0,7222695916,https://prescott.craigslist.org/cto/d/prescott...,prescott,https://prescott.craigslist.org,6000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,az,NaN,NaN,NaN
1,7218891961,https://fayar.craigslist.org/ctd/d/bentonville...,fayetteville,https://fayar.craigslist.org,11900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ar,NaN,NaN,NaN
2,7221797935,https://keys.craigslist.org/cto/d/summerland-k...,florida keys,https://keys.craigslist.org,21000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fl,NaN,NaN,NaN
3,7222270760,https://worcester.craigslist.org/cto/d/west-br...,worcester / central MA,https://worcester.craigslist.org,1500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ma,NaN,NaN,NaN
4,7210384030,https://greensboro.craigslist.org/cto/d/trinit...,greensboro,https://greensboro.craigslist.org,4900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nc,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426875,7301591192,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,23590,2019.0,nissan,maxima s sedan 4d,good,6 cylinders,gas,32226.0,clean,other,1N4AA6AV6KC367801,fwd,NaN,sedan,NaN,https://images.craigslist.org/00o0o_iiraFnHg8q...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:31-0600
426876,7301591187,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,30590,2020.0,volvo,s60 t5 momentum sedan 4d,good,NaN,gas,12029.0,clean,other,7JR102FKXLG042696,fwd,NaN,sedan,red,https://images.craigslist.org/00x0x_15sbgnxCIS...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:29-0600
426877,7301591147,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,34990,2020.0,cadillac,xt4 sport suv 4d,good,NaN,diesel,4174.0,clean,other,1GYFZFR46LF088296,NaN,NaN,hatchback,white,https://images.craigslist.org/00L0L_farM7bxnxR...,Carvana is the safer way to buy a car During t...,NaN,wy,33.779214,-84.411811,2021-04-04T03:21:17-0600
426878,7301591140,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,28990,2018.0,lexus,es 350 sedan 4d,good,6 cylinders,gas,30112.0,clean,other,58ABK1GG4JU103853,fwd,NaN,sedan,silver,https://images.craigslist.org/00z0z_bKnIVGLkDT...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:11-0600
426879,7301591129,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,30590,2019.0,bmw,4 series 430i gran coupe,good,NaN,gas,22716.0,clean,other,WBA4J1C58KBM14708,rwd,NaN,coupe,NaN,https://images.craigslist.org/00Y0Y_lEUocjyRxa...,Carvana is the safer way to buy a car During t...,NaN,wy,33.779214,-84.411811,2021-04-04T03:21:07-0600

In [85]:
data=data.drop(columns=["id","url","region_url","lat","long","paint_color","image_url","description","VIN","posting_date","region","county"])

In [86]:
pd.set_option('display.max_columns', None)
data.tail(5)

,price,year,manufacturer,model,condition,cylinders,fuel,odometer,title_status,transmission,drive,size,type,state
426875,23590,2019.0,nissan,maxima s sedan 4d,good,6 cylinders,gas,32226.0,clean,other,fwd,NaN,sedan,wy
426876,30590,2020.0,volvo,s60 t5 momentum sedan 4d,good,NaN,gas,12029.0,clean,other,fwd,NaN,sedan,wy
426877,34990,2020.0,cadillac,xt4 sport suv 4d,good,NaN,diesel,4174.0,clean,other,NaN,NaN,hatchback,wy
426878,28990,2018.0,lexus,es 350 sedan 4d,good,6 cylinders,gas,30112.0,clean,other,fwd,NaN,sedan,wy
426879,30590,2019.0,bmw,4 series 430i gran coupe,good,NaN,gas,22716.0,clean,other,rwd,NaN,coupe,wy

In [87]:
data.info()
data["transmission"].unique()
data["state"].unique()

<class 'pandas.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   price         426880 non-null  int64
 1   year          425675 non-null  float64
 2   manufacturer  409234 non-null  str
 3   model         421603 non-null  str
 4   condition     252776 non-null  str
 5   cylinders     249202 non-null  str
 6   fuel          423867 non-null  str
 7   odometer      422480 non-null  float64
 8   title_status  418638 non-null  str
 9   transmission  424324 non-null  str
 10  drive         296313 non-null  str
 11  size          120519 non-null  str
 12  type          334022 non-null  str
 13  state         426880 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 45.6 MB

<StringArray>
['az', 'ar', 'fl', 'ma', 'nc', 'ny', 'or', 'pa', 'tx', 'wa', 'wi', 'al', 'ak',
 'ca', 'co', 'ct', 'dc', 'de', 'ga', 'hi', 'id', 'il', 'in', 'ia', 'ks', 'ky',
 'la', 'me', 'md', 'mi', 'mn', 'ms', 'mo', 'mt', 'ne', 'nv', 'nj', 'nm', 'nh',
 'nd', 'oh', 'ok', 'ri', 'sc', 'sd', 'tn', 'ut', 'vt', 'va', 'wv', 'wy']
Length: 51, dtype: str

In [88]:
#data.tail().sort_values(by="model")
boolean= not data["model"].is_unique
boolean

True

In [89]:
mask_man = data[["manufacturer", "model"]].dropna()
model2man=dict(zip(mask_man["model"], mask_man["manufacturer"]))
data["manufacturer"]=data["manufacturer"].fillna(data["model"].map(model2man))
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   price         426880 non-null  int64
 1   year          425675 non-null  float64
 2   manufacturer  410002 non-null  str
 3   model         421603 non-null  str
 4   condition     252776 non-null  str
 5   cylinders     249202 non-null  str
 6   fuel          423867 non-null  str
 7   odometer      422480 non-null  float64
 8   title_status  418638 non-null  str
 9   transmission  424324 non-null  str
 10  drive         296313 non-null  str
 11  size          120519 non-null  str
 12  type          334022 non-null  str
 13  state         426880 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 45.6 MB

In [90]:
data.duplicated().any()
data=data.drop_duplicates()
data.info()

<class 'pandas.DataFrame'>
Index: 298865 entries, 0 to 426879
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   price         298865 non-null  int64
 1   year          297996 non-null  float64
 2   manufacturer  286407 non-null  str
 3   model         294619 non-null  str
 4   condition     185416 non-null  str
 5   cylinders     182847 non-null  str
 6   fuel          296984 non-null  str
 7   odometer      296202 non-null  float64
 8   title_status  294161 non-null  str
 9   transmission  297262 non-null  str
 10  drive         210683 non-null  str
 11  size          94675 non-null   str
 12  type          230068 non-null  str
 13  state         298865 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 34.2 MB

In [92]:
mask_size=data[["size", "model"]].dropna()
size_dict=dict(zip(mask_size["model"], mask_size["size"]))
data["size"]=data["size"].fillna(data["model"].map(size_dict))

data.info()

<class 'pandas.DataFrame'>
Index: 298865 entries, 0 to 426879
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   price         298865 non-null  int64
 1   year          297996 non-null  float64
 2   manufacturer  286407 non-null  str
 3   model         294619 non-null  str
 4   condition     185416 non-null  str
 5   cylinders     182847 non-null  str
 6   fuel          296984 non-null  str
 7   odometer      296202 non-null  float64
 8   title_status  294161 non-null  str
 9   transmission  297262 non-null  str
 10  drive         210683 non-null  str
 11  size          242947 non-null  str
 12  type          230068 non-null  str
 13  state         298865 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 34.2 MB

In [93]:
mask_size=data[["model", "drive"]].dropna()
size_dict=dict(zip(mask_size["model"], mask_size["drive"]))
data["drive"]=data["drive"].fillna(data["model"].map(size_dict))

data.info()

<class 'pandas.DataFrame'>
Index: 298865 entries, 0 to 426879
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   price         298865 non-null  int64
 1   year          297996 non-null  float64
 2   manufacturer  286407 non-null  str
 3   model         294619 non-null  str
 4   condition     185416 non-null  str
 5   cylinders     182847 non-null  str
 6   fuel          296984 non-null  str
 7   odometer      296202 non-null  float64
 8   title_status  294161 non-null  str
 9   transmission  297262 non-null  str
 10  drive         282213 non-null  str
 11  size          242947 non-null  str
 12  type          230068 non-null  str
 13  state         298865 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 34.2 MB

In [94]:
mask_size=data[["model", "type"]].dropna()
size_dict=dict(zip(mask_size["model"], mask_size["type"]))
data["type"]=data["type"].fillna(data["model"].map(size_dict))

data.info()

<class 'pandas.DataFrame'>
Index: 298865 entries, 0 to 426879
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   price         298865 non-null  int64
 1   year          297996 non-null  float64
 2   manufacturer  286407 non-null  str
 3   model         294619 non-null  str
 4   condition     185416 non-null  str
 5   cylinders     182847 non-null  str
 6   fuel          296984 non-null  str
 7   odometer      296202 non-null  float64
 8   title_status  294161 non-null  str
 9   transmission  297262 non-null  str
 10  drive         282213 non-null  str
 11  size          242947 non-null  str
 12  type          289765 non-null  str
 13  state         298865 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 34.2 MB

In [95]:
mask_size = data[["model", "cylinders"]].dropna()
size_dict = dict(zip(mask_size["model"], mask_size["cylinders"]))
data["cylinders"] = data["cylinders"].fillna(data["model"].map(size_dict))

data.info()

<class 'pandas.DataFrame'>
Index: 298865 entries, 0 to 426879
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   price         298865 non-null  int64
 1   year          297996 non-null  float64
 2   manufacturer  286407 non-null  str
 3   model         294619 non-null  str
 4   condition     185416 non-null  str
 5   cylinders     273027 non-null  str
 6   fuel          296984 non-null  str
 7   odometer      296202 non-null  float64
 8   title_status  294161 non-null  str
 9   transmission  297262 non-null  str
 10  drive         282213 non-null  str
 11  size          242947 non-null  str
 12  type          289765 non-null  str
 13  state         298865 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 34.2 MB

In [96]:
mask_size = data[["model", "condition"]].dropna()
size_dict = dict(zip(mask_size["model"], mask_size["condition"]))
data["condition"] = data["condition"].fillna(data["model"].map(size_dict))

data.info()

<class 'pandas.DataFrame'>
Index: 298865 entries, 0 to 426879
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   price         298865 non-null  int64
 1   year          297996 non-null  float64
 2   manufacturer  286407 non-null  str
 3   model         294619 non-null  str
 4   condition     282029 non-null  str
 5   cylinders     273027 non-null  str
 6   fuel          296984 non-null  str
 7   odometer      296202 non-null  float64
 8   title_status  294161 non-null  str
 9   transmission  297262 non-null  str
 10  drive         282213 non-null  str
 11  size          242947 non-null  str
 12  type          289765 non-null  str
 13  state         298865 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 34.2 MB